# Generated by Django 3.2 on 2023-04-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_authenticator'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancellphone',
            name='number_of_try',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banip',
            name='number_of_try',
            field=models.IntegerField(default=0),
        ),
    ]
