# Generated by Django 3.2 on 2023-04-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20230413_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticator',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authenticator',
            name='sms_verified',
            field=models.BooleanField(default=False),
        ),
    ]
