# Generated by Django 3.2 on 2023-04-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20230413_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bancellphone',
            old_name='ban_time',
            new_name='ban_date_time',
        ),
        migrations.RenameField(
            model_name='banip',
            old_name='ban_time',
            new_name='ban_date_time',
        ),
    ]
